import {describe,it,expect} from 'vitest';
import {seed,transition as t,forecast,cohort,accepted,currentEvidence,restore,compare,exportSession,type State} from '../domain/engine';
const recover=(s:State)=>{for(const a of [{type:'inject'},{type:'assign'},{type:'diagnose'},{type:'recover'},{type:'verifyCore'}])s=t(s,a);return s;};
const s1=()=>{let s=recover(t(seed(),{type:'agree'}));s=t(s,{type:'submit',count:10});s=t(s,{type:'advance',seconds:40});s=t(s,{type:'verifyJob',id:s.jobs.find(j=>j.status==='needs_verification')!.id});return s;};
describe('domain invariants',()=>{
it('S1 completes exactly ten effects, bounded transient retry, explicit acceptance and renewal',()=>{let s=s1();expect(s.jobs.every(j=>j.status==='succeeded')).toBe(true);expect(Object.values(s.remote).reduce((n,r)=>n+r.effects,0)).toBe(10);expect(s.jobs[8].attempts).toBe(2);expect(s.jobs[9].attempts).toBe(1);s=t(s,{type:'generate'});s=t(s,{type:'validate'});expect(accepted(s)).toBe(false);s=t(s,{type:'accept'});expect(s.notice).toContain('Customer reviewer');s=t(s,{type:'role',value:'Customer reviewer'});s=t(s,{type:'accept'});expect(accepted(s)).toBe(true);expect(s.accounts[0].contract).toBe('not_started');s=t(s,{type:'role',value:'Finance / decision owner'});s=t(s,{type:'decision',value:'renewed',owner:'Nadia',note:'Demo'});expect(s.accounts[0].contract).toBe('renewed');expect(s.accounts.slice(1).every(a=>a.contract==='not_started')).toBe(true);});
it('atomic acceptance and durable outbox on publisher failure',()=>{let s=t(seed(),{type:'submit',commitFailed:true});expect(s.jobs).toHaveLength(0);expect(s.outbox).toHaveLength(0);s=t(s,{type:'publisher',failed:true});s=t(s,{type:'submit'});s=t(s,{type:'advance',seconds:2});expect(s.jobs[0].status).toBe('accepted');expect(s.outbox[0].state).toBe('pending');s=t(s,{type:'publisher',failed:false});s=t(s,{type:'advance'});expect(s.jobs[0].status).toBe('queued');expect(s.events.findIndex(e=>e.type==='outbox')).toBeLessThan(s.events.findIndex(e=>e.type==='accepted'));});
it('ambiguous outcome blocks blind replay',()=>{let s=recover(seed());s=t(s,{type:'submit',fault:'ambiguous'});s=t(s,{type:'advance',seconds:6});s=t(s,{type:'retry',id:s.jobs[0].id});expect(s.notice).toContain('Jangan blind resend');expect(s.jobs[0].status).toBe('needs_verification');expect(Object.values(s.remote)[0].effects).toBe(1);});
it('permanent failure and exhausted retries stop automatically',()=>{for(const fault of ['permanent','exhausted']){let s=t(recover(seed()),{type:'submit',fault});s=t(s,{type:'advance',seconds:90});expect(s.jobs[0].status).toBe('needs_attention');expect(s.jobs[0].attempts).toBe(fault==='permanent'?1:3);}});
it('duplicate operation and old entity version cannot add effects',()=>{let s=recover(seed());s=t(s,{type:'submit',operationId:'stable',entity:'X',version:3});s=t(s,{type:'advance',seconds:6});s=t(s,{type:'submit',operationId:'stable',entity:'X',version:3});expect(s.jobs).toHaveLength(1);s=t(s,{type:'submit',entity:'X',version:1});s=t(s,{type:'advance',seconds:6});expect(s.remote['toko:X'].version).toBe(3);expect(s.remote['toko:X'].effects).toBe(1);});
it('S3 failure leaves checkpoint/watermark/rows unchanged; replay applies update late update delete once',()=>{let s=t(seed(),{type:'scenario',scenario:'S3'});const old=structuredClone(s.pipeline);s=t(s,{type:'batch'});s=t(s,{type:'advance',seconds:3});expect(s.pipeline.status).toBe('failed');expect(s.pipeline.checkpoint).toBe(old.checkpoint);expect(s.pipeline.through).toBe(old.through);expect(s.pipeline.rows).toEqual(old.rows);s=t(s,{type:'refresh'});expect(s.pipeline.through).toBe(old.through);s=t(s,{type:'mapping'});s=t(s,{type:'batch'});s=t(s,{type:'advance',seconds:3});expect(s.pipeline.checkpoint).toBe(103);expect(s.pipeline.rows).toEqual({'T-01':2,'T-02':3});const rows=s.pipeline.rows;s=t(s,{type:'batch'});s=t(s,{type:'advance',seconds:3});expect(s.pipeline.rows).toEqual(rows);});
it('S2 failover is guarded, verification is required, manual compliance remains missing',()=>{let s=t(seed(),{type:'scenario',scenario:'S2'});for(const type of ['agree','inject','assign','diagnose','recover'])s=t(s,{type});expect(s.core.incident).toBe('diagnosed');s=t(s,{type:'prepare'});s=t(s,{type:'recover'});expect(s.core.status).toBe('failed');s=t(s,{type:'verifyCore'});s=t(s,{type:'fixture'});s=t(s,{type:'generate'});s=t(s,{type:'validate'});expect(currentEvidence(s).find(e=>e.criterionId==='access')!.validation).toBe('missing');expect(currentEvidence(s).find(e=>e.criterionId==='uptime')!.value).toBeCloseTo(99.960317);});
it('account selection never moves jobs/evidence; edits invalidate prior acceptance',()=>{let s=s1();for(const a of [{type:'generate'},{type:'validate'},{type:'role',value:'Customer reviewer'},{type:'accept'}])s=t(s,a);const criteria=s.accounts[0].criteria;s=t(s,{type:'editCovenant',criteria});expect(accepted(s)).toBe(false);expect(s.evidence[0].customerReview).toBe('accepted');expect(s.evidence[0].validation).toBe('outdated');s=t(s,{type:'select',id:'bank'});expect(cohort(s)).toHaveLength(0);expect(currentEvidence(s)).toHaveLength(0);expect(s.jobs[0].accountId).toBe('toko');});
it('strict thresholds and missing data are not fabricated',()=>{const c=seed().accounts[4].criteria[0];expect(compare(1,c)).toBe(false);expect(compare(1,{...c,op:'<='})).toBe(true);let s=t(seed(),{type:'agree'});s=t(s,{type:'generate'});expect(currentEvidence(s).every(e=>e.value===null)).toBe(true);});
it('longer observation duration remains incomplete; fixture leaves live watermark untouched',()=>{let s=t(recover(seed()),{type:'select',id:'logistik'});s=t(s,{type:'editCovenant',criteria:s.accounts[4].criteria.map(c=>({...c,duration:1209600}))});s=t(s,{type:'agree'});const old=s.pipeline.through;s=t(s,{type:'fixture'});expect(s.pipeline.through).toBe(old);s=t(s,{type:'generate'});s=t(s,{type:'validate'});expect(currentEvidence(s)[0].validation).toBe('incomplete');});
it('shared forecast defaults, optional cap, mandatory liability and reallocation',()=>{let s=seed();expect(forecast(s)).toBe(520);expect(750-forecast(s)).toBe(230);expect(s.ledger.reduce((n,l)=>n+l.monthly,0)).toBe(40);s=t(s,{type:'cost',id:'goodwill',amount:300,kind:'optional'});expect(forecast(s)).toBe(520);s=t(s,{type:'cost',id:'liability',amount:300,kind:'mandatory'});expect(forecast(s)).toBe(820);s=t(s,{type:'cost',id:'liability',amount:300,kind:'mandatory'});expect(forecast(s)).toBe(820);s=t(s,{type:'reallocate',amount:10});expect(forecast(s)).toBe(820);s=t(s,{type:'resetRun'});expect(forecast(s)).toBe(820);});
it('reload restores paused, rejects corrupt schema, export is explicitly simulated',()=>{let s=s1();s=t(s,{type:'play'});const restored=restore(JSON.stringify(s));expect(restored.running).toBe(false);expect(restored.remote).toEqual(s.remote);expect(()=>restore('{"schemaVersion":99}')).toThrow();expect(exportSession(s).simulation).toBe(true);s=t(s,{type:'pause'});const time=s.run.now;s=t(s,{type:'tick'});expect(s.run.now).toBe(time);});
});
it('regenerating evidence creates distinct identities and refund edits preserve other accounts',()=>{let s=s1();s=t(s,{type:'generate'});s=t(s,{type:'generate'});expect(new Set(s.evidence.map(e=>e.id)).size).toBe(s.evidence.length);s=t(s,{type:'refund',fee:100,months:1,eligible:true});const first=s.ledger.find(l=>l.id==='refund')!.allowance;s=t(s,{type:'select',id:'tele'});s=t(s,{type:'refund',fee:50,months:2,eligible:true});expect(s.ledger.find(l=>l.id==='refund')!.allowance).toBe(first);expect(s.ledger.find(l=>l.id==='refund')!.refundByAccount!.toko).toBe(15);});
