export type AccountId = 'toko'|'bank'|'tele'|'medika'|'logistik';
export type Scenario = 'S1'|'S2'|'S3';
export type Criterion = {id:string; label:string; metric:string; op:'<'|'<='|'>='|'='; threshold:number; unit:string; duration:number; reviewer:string; exclusions:string};
export type Account = {id:AccountId;name:string;short:string;arr:number;months:number;concern:string;owner:string;version:number;agreed:boolean;criteria:Criterion[];intent:string;contract:string;decisionNote:string;decisionOwner:string;decisionAt?:number};
export type Job = {id:string;runId:string;accountId:AccountId;operationId:string;entityId:string;version:number;payload:string;status:string;acceptedAt:number;attempts:number;nextAttemptAt:number;deadlineAt:number;completedAt?:number;finishAt?:number;fault:string;reason:string};
export type Event = {id:string;sequence:number;runId:string;accountId:AccountId|'platform';simulatedAt:number;solution:string;type:string;entityRef:string;message:string};
export type Evidence = {id:string;accountId:AccountId;criterionId:string;covenantVersion:number;runId:string;sourceRefs:string[];window:{start:number;end:number;duration:number};value:number|null;unit:string;provenance:string;validation:string;customerReview:string;note:string;owner:string};
export type Ledger = {id:string;category:string;oneOff:number;monthly:number;months:number;allowance:number;committed:number;spent:number;refundByAccount?:Record<string,number>;kind:string};
export type State = {schemaVersion:1;selected:AccountId;role:string;mode:string;running:boolean;speed:number;step:number;notice:string;accounts:Account[];run:{id:string;scenario:Scenario;accountId:AccountId;now:number;seed:number};archives:unknown[];core:{status:string;standby:boolean;readiness:boolean;backup:boolean;owner:string;incident:string;detectedAt:number;resolvedAt?:number;capacity:number;samples:{t:number;cpu:number;db:number}[]};jobs:Job[];outbox:{jobId:string;createdAt:number;state:string;attempts:number}[];remote:Record<string,{version:number;operations:string[];effects:number}>;pipeline:{checkpoint:number;through:number;publishedAt:number;refreshAt:number;status:string;mapping:boolean;coverage:string[];rows:Record<string,number>;due:number;finishAt:number|null};workers:number;publisherFailed:boolean;evidence:Evidence[];fixtures:{id:string;accountId:AccountId;runId:string;failed:number;manual:boolean}[];ledger:Ledger[];events:Event[];gaps:{id:string;accountId:AccountId;owner:string;note:string}[]};
const c=(id:string,label:string,metric:string,op:Criterion['op'],threshold:number,unit:string,duration=0):Criterion=>({id,label,metric,op,threshold,unit,duration,reviewer:'Customer reviewer',exclusions:'Tidak ada; seluruh cohort demo'});
export function seed():State {const accounts:Account[]=[
{id:'toko',name:'TokoCepat',short:'TC',arr:1500,months:8,concern:'Throughput & sinkronisasi tiket',owner:'Nadia · Customer Success',criteria:[c('jobs','Seluruh pekerjaan terverifikasi','completion','>=',100,'%'),c('deadline','Penyelesaian tepat waktu','latency','<=',60,'detik'),c('reconcile','Selisih rekonsiliasi','mismatch','=',0,'selisih')]},
{id:'bank',name:'Bank FinNusantara',short:'BN',arr:2000,months:4,concern:'Keamanan, compliance & uptime',owner:'Arif · Account Lead',criteria:[c('uptime','Availability periode bukti','availability','>=',99.9,'%',604800),c('recovery','Uji recovery & integritas','recovery','=',1,'lulus'),c('access','Review akses & audit trail','manual','=',1,'review'),c('location','Review lokasi data Indonesia','manual','=',1,'review')]},
{id:'tele',name:'TeleNusa',short:'TN',arr:1200,months:2,concern:'Dashboard real-time & lengkap',owner:'Dimas · Account Lead',criteria:[c('fresh','Freshness sumber wajib','freshness','<=',15,'menit'),c('complete','Kelengkapan data','completeness','=',100,'%')]},
{id:'medika',name:'MedikaCare',short:'MC',arr:900,months:6,concern:'Latensi & operasional medis',owner:'Sari · Account Lead',criteria:[c('mean','Mean critical-path latency','mean','<',1000,'ms',604800),c('error','Keberhasilan critical path','error','<=',1,'%',604800),c('medical','Review operasional medis','manual','=',1,'review')]},
{id:'logistik',name:'LogistikGo',short:'LG',arr:400,months:1,concern:'API error harus <1%',owner:'Raka · Account Lead',criteria:[c('error','Error rate akun','error','<',1,'%',604800),c('jobs','Accepted work selesai','completion','=',100,'%')]}
].map(a=>({...a,version:1,agreed:false,intent:'not_discussed',contract:'not_started',decisionNote:'',decisionOwner:''})) as Account[];
return {schemaVersion:1,selected:'toko',role:'Presenter',mode:'guided',running:false,speed:1,step:0,notice:'',accounts,run:{id:'run-001',scenario:'S1',accountId:'toko',now:0,seed:42},archives:[],core:{status:'constrained',standby:false,readiness:false,backup:true,owner:'',incident:'none',detectedAt:0,capacity:0,samples:[{t:0,cpu:92,db:98}]},jobs:[],outbox:[],remote:{},pipeline:{checkpoint:100,through:-43200,publishedAt:-43200,refreshAt:0,status:'idle',mapping:true,coverage:['CRM','ERP'],rows:{'T-01':1,'T-02':1,'T-03':1},due:300,finishAt:null},workers:2,publisherFailed:false,evidence:[],fixtures:[],ledger:[['core','Core',140,20,2,0,'one-off'],['flow','Integration / data',100,10,2,0,'one-off'],['ops','Shared operations',40,10,2,0,'recurring'],['refund','Provisi refund kontraktual',0,0,0,75,'mandatory'],['goodwill','Goodwill opsional',0,0,0,25,'optional'],['reserve','Cadangan kontingensi',0,0,0,60,'reserve']].map(([id,category,oneOff,monthly,months,allowance,kind])=>({id,category,oneOff,monthly,months,allowance,kind,committed:0,spent:0})) as Ledger[],events:[],gaps:[]};}
export type Action = {type:string;[key:string]:unknown};
export const forecast=(s:State)=>s.ledger.reduce((n,l)=>n+l.oneOff+l.monthly*l.months+l.allowance,0);
export const compare=(v:number,c:Criterion)=>c.op==='<'?v<c.threshold:c.op==='<='?v<=c.threshold:c.op==='>='?v>=c.threshold:v===c.threshold;
export const account=(s:State)=>s.accounts.find(a=>a.id===s.selected)!;
export const cohort=(s:State)=>s.jobs.filter(j=>j.accountId===s.selected&&j.runId===s.run.id);
export const currentEvidence=(s:State)=>s.evidence.filter(e=>e.accountId===s.selected&&e.runId===s.run.id&&e.covenantVersion===account(s).version);
export const accepted=(s:State)=>account(s).agreed&&account(s).criteria.every(c=>currentEvidence(s).some(e=>e.criterionId===c.id&&e.customerReview==='accepted'));
function event(s:State,type:string,message:string,entityRef='',scope:AccountId|'platform'=s.selected,solution='Trust'){const sequence=s.events.length+1;s.events.push({id:`evt-${sequence}`,sequence,runId:s.run.id,accountId:scope,simulatedAt:s.run.now,solution,type,entityRef,message});}
function applyRemote(s:State,j:Job){const key=`${j.accountId}:${j.entityId}`;const r=s.remote[key]??{version:0,operations:[],effects:0};if(r.operations.includes(j.operationId)){j.reason='Duplikat diabaikan; efek bisnis tetap satu.';}else if(j.version<=r.version){j.reason='Versi lama diabaikan; data terbaru dipertahankan.';r.operations.push(j.operationId);}else{r.version=j.version;r.operations.push(j.operationId);r.effects++;j.reason='Efek bisnis diterapkan satu kali.';}s.remote[key]=r;event(s,'remote',j.reason,j.id,j.accountId,'Flow');}
function tick(s:State){s.run.now++;const now=s.run.now;
if(!s.publisherFailed)for(const o of s.outbox.filter(o=>o.state==='pending')){o.state='dispatched';o.attempts++;const j=s.jobs.find(j=>j.id===o.jobId)!;j.status='queued';event(s,'dispatch','Outbox dipublikasikan ke antrean.',j.id,j.accountId,'Flow');}
if(s.core.status==='healthy'){
for(const j of s.jobs.filter(j=>j.status==='running'&&j.finishAt!<=now)){
if(j.fault==='permanent'||(j.fault==='exhausted')||(j.fault==='transient'&&j.attempts===1)){if(j.fault==='permanent'||j.attempts>=3){j.status='needs_attention';j.reason='Batas retry / validasi permanen. Koreksi payload diperlukan.';}else{j.status='retry_wait';j.nextAttemptAt=now+Math.min(8,2**j.attempts);j.reason='Gangguan sementara; retry terjadwal.';}event(s,'attempt_failed',j.reason,j.id,j.accountId,'Flow');}
else{applyRemote(s,j);j.status=j.fault==='ambiguous'?'needs_verification':'succeeded';if(j.status==='succeeded')j.completedAt=now;else j.reason='Remote mungkin commit; acknowledgment hilang. Verifikasi sebelum retry.';event(s,j.status,j.reason,j.id,j.accountId,'Flow');}}
const active=s.jobs.filter(j=>j.status==='running').length;let slots=Math.min(s.workers,s.core.capacity,2)-active;
for(const j of s.jobs.filter(j=>j.status==='queued'||j.status==='retry_wait'&&j.nextAttemptAt<=now).sort((a,b)=>a.attempts-b.attempts||a.acceptedAt-b.acceptedAt)){if(slots--<=0)break;j.status='running';j.attempts++;j.finishAt=now+4;event(s,'running',`Percobaan ${j.attempts}; respons remote 4 detik.`,j.id,j.accountId,'Flow');}}
if(s.pipeline.finishAt!==null&&s.pipeline.finishAt<=now){s.pipeline.finishAt=null;if(!s.pipeline.mapping){s.pipeline.status='failed';event(s,'batch_failed','Validasi schema gagal. Publikasi dan checkpoint tetap.', 'pipeline',s.run.accountId,'Flow');}else{const p=s.pipeline;p.rows={'T-01':2,'T-02':3};p.checkpoint=103;p.through=now;p.publishedAt=now;p.coverage=['CRM','ERP'];p.status='published';event(s,'published','Update, late update, dan tombstone dipublikasikan atomik; checkpoint 103.','pipeline',s.run.accountId,'Flow');}s.pipeline.due=now+300;}
if(now>=s.pipeline.due&&s.pipeline.finishAt===null&&s.core.status==='healthy'){s.pipeline.status='extracting';s.pipeline.finishAt=now+3;s.pipeline.due=now+300;}
}
function metric(s:State,c:Criterion):{value:number|null;duration:number;refs:string[]}{const jobs=cohort(s),f=s.fixtures.find(f=>f.runId===s.run.id&&f.accountId===s.selected&&!f.manual),manual=s.fixtures.find(f=>f.runId===s.run.id&&f.accountId===s.selected&&f.manual);const refs=s.events.filter(e=>e.runId===s.run.id&&(e.accountId===s.selected||e.accountId==='platform')).map(e=>e.id);let value:number|null=null,duration=s.run.now;
switch(c.metric){case 'completion':value=jobs.length?jobs.filter(j=>j.status==='succeeded').length/jobs.length*100:null;break;case 'latency':value=jobs.length&&jobs.every(j=>j.status==='succeeded')?Math.max(...jobs.map(j=>j.completedAt!-j.acceptedAt)):null;break;case 'mismatch':value=jobs.length?jobs.filter(j=>j.status!=='succeeded').length:null;break;case 'recovery':value=s.core.incident==='resolved'&&s.selected===s.run.accountId?1:null;break;case 'freshness':value=s.pipeline.status==='published'&&s.pipeline.coverage.length===2&&s.selected===s.run.accountId?(s.run.now-s.pipeline.through)/60:null;break;case 'completeness':value=s.pipeline.status==='published'&&s.pipeline.coverage.length===2&&s.selected===s.run.accountId?100:null;break;case 'manual':value=manual?1:null;if(manual)refs.push(manual.id);break;case 'availability':case 'error':case 'mean':if(f){value=c.metric==='availability'?(604800-240)/604800*100:c.metric==='error'?f.failed/1000*100:500000/1000;duration=604800;refs.push(f.id);}break;}return {value,duration,refs};}
export function transition(old:State,a:Action):State {if(a.type==='tick'&&!old.running)return old;if(a.type==='pause'&&!old.running)return old;if(a.type==='resetAll')return seed();const s=structuredClone(old);s.notice='';const fail=(m:string)=>{s.notice=m;return s;};const ac=account(s);switch(a.type){
case 'select':if(s.accounts.some(x=>x.id===a.id))s.selected=a.id as AccountId;break;
case 'role':s.role=String(a.value);break;case 'mode':s.mode=String(a.value);s.running=false;break;case 'speed':s.speed=Number(a.value);break;case 'play':s.running=!s.running;break;case 'pause':s.running=false;break;
case 'tick':if(s.running)for(let i=0;i<s.speed;i++)tick(s);break;case 'advance':for(let i=0;i<Number(a.seconds??1);i++)tick(s);break;
case 'step':s.step=Math.min(8,s.step+1);s.running=false;break;
case 'scenario':case 'resetRun':{const scenario=(a.scenario??s.run.scenario) as Scenario;const fresh=seed();const id=`run-${String(s.archives.length+2).padStart(3,'0')}`;s.archives.push({run:s.run,core:s.core,jobs:s.jobs,outbox:s.outbox,remote:s.remote,pipeline:s.pipeline,fixtures:s.fixtures});s.run={...fresh.run,id,scenario,accountId:scenario==='S1'?'toko':scenario==='S2'?'bank':'tele'};s.selected=s.run.accountId;s.core=fresh.core;s.pipeline=fresh.pipeline;s.pipeline.mapping=scenario!=='S3';if(scenario==='S3'){s.core.status='healthy';s.core.capacity=2;}s.jobs=[];s.outbox=[];s.remote={};s.running=false;s.step=0;s.publisherFailed=false;s.notice='Run baru. Bukti lama menjadi historis; keputusan dan ledger tetap tersimpan.';event(s,'run','Run baru dimulai.');break;}
case 'agree':ac.agreed=true;event(s,'covenant_agreed',`Covenant v${ac.version} disepakati sebagai asumsi demo.`);break;
case 'editCovenant':{const criteria=a.criteria as Criterion[];if(!criteria.length||criteria.some(c=>!Number.isFinite(c.threshold)||c.threshold<0||!Number.isFinite(c.duration)||c.duration<0||!c.reviewer.trim()))return fail('Threshold, durasi, dan reviewer harus valid.');ac.criteria=criteria;ac.version++;ac.agreed=false;for(const e of s.evidence.filter(e=>e.accountId===s.selected))e.validation='outdated';event(s,'covenant_changed',`Covenant v${ac.version}; review terdahulu tetap historis.`);break;}
case 'prepare':s.core.standby=true;s.core.readiness=true;event(s,'prepared','Standby usulan: readiness dan data check lulus.','core','platform','Core');break;
case 'inject':if(s.core.incident!=='none')return fail('Insiden sudah dibuat untuk run ini.');s.core.incident='detected';s.core.detectedAt=s.run.now;s.core.status=s.run.scenario==='S2'?'failed':'constrained';s.core.capacity=0;event(s,'incident','Alert langsung: '+(s.run.scenario==='S2'?'komponen database gagal.':'connection pool tertekan oleh workload contoh.'),'core','platform','Core');break;
case 'assign':if(s.core.incident!=='detected')return fail('Deteksi insiden terlebih dahulu.');s.core.owner=String(a.owner??'Rafi · DevOps');s.core.incident='assigned';event(s,'assigned',`Incident commander: ${s.core.owner}`,'core','platform','Core');break;
case 'diagnose':if(s.core.incident!=='assigned'&&s.core.incident!=='diagnosed')return fail('Tetapkan pemilik insiden sebelum diagnosis.');s.core.incident='diagnosed';event(s,'diagnosed',s.run.scenario==='S2'?'Primary database tidak siap; standby terpisah dari read replica dan backup.':'Query berat menahan koneksi; batasi workload dan connection pool.','core','platform','Core');break;
case 'recover':if(s.core.incident!=='diagnosed'||!s.core.owner)return fail('Diagnosis dan incident owner diperlukan.');if(a.playbook==='rollback')return fail('Rollback tidak cocok: tidak ada penyebab perubahan deployment.');if(s.run.scenario==='S2'&&a.playbook!=='restore'&&(!s.core.standby||!s.core.readiness))return fail('Failover membutuhkan standby dan readiness/data check.');if(a.playbook==='restore'&&!s.core.backup)return fail('Backup fixture tidak valid.');s.core.incident='verifying';event(s,'recovery_action','Mitigasi dijalankan; menunggu verifikasi layanan dan integritas.','core','platform','Core');break;
case 'verifyCore':if(s.core.incident!=='verifying')return fail('Jalankan recovery sebelum verifikasi.');if(a.failed){s.core.incident='diagnosed';s.core.status='failed';event(s,'verification_failed','Integrity check gagal; kembali ke diagnosis.','core','platform','Core');}else{s.core.incident='resolved';s.core.status='healthy';s.core.capacity=2;s.core.resolvedAt=s.run.now;s.core.samples.push({t:s.run.now,cpu:54,db:61});event(s,'verified','Service readiness dan integrity check lulus. Worker budget: 2.','core','platform','Core');}break;
case 'workers':if(Number(a.value)>2||Number(a.value)<1)return fail('Dibatasi: kapasitas core dan kuota remote maksimum 2.');s.workers=Number(a.value);break;
case 'publisher':s.publisherFailed=Boolean(a.failed);break;
case 'submit':{if(a.commitFailed)return fail('Commit lokal gagal: tidak ada job diterima atau outbox dibuat.');if(a.mode==='sync'){if(s.core.status!=='healthy')return fail('Respons otoritatif sync gagal: layanan belum siap.');event(s,'sync','Operasi otoritatif selesai sinkron; tidak masuk antrean.','',''+s.selected as AccountId,'Flow');s.notice='Respons otoritatif diterima secara sinkron.';break;}const count=Number(a.count??1);if(count===10&&s.jobs.some(j=>j.operationId==='sample-1'))return fail('Cohort contoh sudah diterima. Gunakan run baru untuk cohort baru.');if(!String(a.entity??'T').trim()||Number(a.version??1)<1)return fail('Entity dan versi positif diperlukan.');for(let i=0;i<count;i++){const operationId=count===10?`sample-${i+1}`:String(a.operationId??`op-${s.jobs.length+1}`);if(s.jobs.some(j=>j.accountId===s.selected&&j.operationId===operationId)){event(s,'duplicate','Operation ID sudah diterima; job baru tidak dibuat.',operationId,s.selected,'Flow');continue;}const id=`${s.run.id}-job-${s.jobs.length+1}`;const j:Job={id,runId:s.run.id,accountId:s.selected,operationId,entityId:count===10?`T-${i+1}`:String(a.entity??'T-01'),version:Number(a.version??1),payload:String(a.payload??'Pembaruan status tiket'),status:'accepted',acceptedAt:s.run.now,attempts:0,nextAttemptAt:0,deadlineAt:s.run.now+60,fault:count===10?(i===8?'transient':i===9?'ambiguous':'none'):String(a.fault??'none'),reason:'Commit lokal + outbox tersimpan; belum selesai.'};s.outbox.push({jobId:id,createdAt:s.run.now,state:'pending',attempts:0});event(s,'outbox','Local record dan outbox commit atomik.',id,s.selected,'Flow');s.jobs.push(j);event(s,'accepted','Request diterima; job ID dikembalikan.',id,s.selected,'Flow');}break;}
case 'verifyJob':{const j=s.jobs.find(j=>j.id===a.id);if(!j||j.status!=='needs_verification')return fail('Pilih job dengan hasil ambigu.');const r=s.remote[`${j.accountId}:${j.entityId}`];if(r?.operations.includes(j.operationId)){j.status='succeeded';j.completedAt=s.run.now;j.reason='Remote commit dikonfirmasi tanpa kirim ulang.';}else{j.status='queued';j.fault='none';j.reason='Remote memastikan tidak ada commit; replay aman.';}event(s,'reconciled',j.reason,j.id,j.accountId,'Flow');break;}
case 'retry':{const j=s.jobs.find(j=>j.id===a.id);if(!j)return fail('Job tidak ditemukan.');if(j.status==='needs_verification')return fail('Jangan blind resend. Verifikasi remote result terlebih dahulu.');if(j.status!=='needs_attention')return fail('Hanya job needs_attention yang dapat dikoreksi.');j.fault='none';j.status='queued';j.attempts=0;j.reason='Payload dikoreksi; replay dengan operation ID yang sama.';event(s,'corrected',j.reason,j.id,j.accountId,'Flow');break;}
case 'batch':if(s.core.status!=='healthy')return fail('Pipeline menunggu dependency core sehat.');if(s.pipeline.finishAt!==null)return fail('Satu batch masih berjalan; pemicu digabung.');s.pipeline.status='extracting';s.pipeline.finishAt=s.run.now+3;event(s,'extract','Extract dari checkpoint '+s.pipeline.checkpoint,'pipeline',s.run.accountId,'Flow');break;
case 'mapping':s.pipeline.mapping=true;event(s,'mapping','Mapping schema dikoreksi; replay tetap dari checkpoint terakhir.','pipeline',s.run.accountId,'Flow');break;
case 'refresh':s.pipeline.refreshAt=s.run.now;s.notice='Tampilan diperbarui. Watermark dan checkpoint tidak berubah.';break;
case 'fixture':{if(s.core.status!=='healthy'||cohort(s).some(j=>j.status!=='succeeded'))return fail('Selesaikan recovery dan job relevan sebelum memuat fixture.');s.fixtures=s.fixtures.filter(f=>!(f.accountId===s.selected&&f.runId===s.run.id&&f.manual===Boolean(a.manual)));const f={id:`fixture-${s.events.length+1}`,accountId:s.selected,runId:s.run.id,failed:a.failing?15:5,manual:Boolean(a.manual)};s.fixtures.push(f);event(s,'fixture',f.manual?'Review manual ilustratif dimuat; bukan sertifikasi.':'Periode agregat 7 hari contoh dimuat; terpisah dari jam live.',f.id);break;}
case 'generate':if(!ac.agreed)return fail('Sepakati covenant terlebih dahulu.');for(const c of ac.criteria){const m=metric(s,c);const e:Evidence={id:`evidence-${s.run.id}-${s.selected}-v${ac.version}-${c.id}-${s.events.length+1}`,accountId:s.selected,criterionId:c.id,covenantVersion:ac.version,runId:s.run.id,sourceRefs:m.refs,window:{start:m.duration===604800?-604800:0,end:m.duration===604800?0:s.run.now,duration:m.duration},value:m.value,unit:c.unit,provenance:m.duration===604800?'Simulasi · fixture 7 hari':'Simulasi · run / review ilustratif',validation:m.value===null?'missing':'collected',customerReview:'pending',note:'',owner:ac.owner};s.evidence=s.evidence.filter(x=>!(x.runId===e.runId&&x.accountId===e.accountId&&x.criterionId===e.criterionId&&x.covenantVersion===e.covenantVersion));s.evidence.push(e);}event(s,'evidence','Bukti dirakit dari sumber run dan fixture yang dipilih.');break;
case 'validate':for(const e of currentEvidence(s)){const c=ac.criteria.find(c=>c.id===e.criterionId)!;e.validation=e.value===null?'missing':e.window.duration<c.duration?'incomplete':compare(e.value,c)?'customer_review_pending':'failed';}event(s,'validation','Scope, versi, durasi, coverage, dan threshold bukti dievaluasi.');break;
case 'accept':if(s.role!=='Customer reviewer')return fail('Gunakan perspektif demo Customer reviewer.');if(!ac.agreed||!ac.criteria.every(c=>currentEvidence(s).some(e=>e.criterionId===c.id&&e.validation==='customer_review_pending')))return fail('Bukti belum memenuhi seluruh kriteria covenant saat ini.');for(const e of currentEvidence(s)){e.customerReview='accepted';e.validation='accepted';}event(s,'accepted_evidence','Pelanggan menerima bukti secara eksplisit.');break;
case 'reject':if(s.role!=='Customer reviewer')return fail('Gunakan perspektif demo Customer reviewer.');for(const e of currentEvidence(s)){e.customerReview='rejected';e.note=String(a.note??'Lengkapi bukti dan review kebutuhan pelanggan.');}s.gaps.push({id:`gap-${s.gaps.length+1}`,accountId:s.selected,owner:ac.owner,note:String(a.note??'Lengkapi bukti; koordinasi Core / Flow dan reviewer manual.')});event(s,'correction','Permintaan perbaikan ditautkan ke pemilik akun.');break;
case 'intent':ac.intent=String(a.value);event(s,'intent',`Intent demo: ${ac.intent}`);break;
case 'decision':if(s.role!=='Finance / decision owner')return fail('Gunakan perspektif demo Finance / decision owner.');if(!accepted(s))return fail('Seluruh bukti covenant aktif harus diterima pelanggan.');if(!String(a.owner??'').trim()||!String(a.note??'').trim())return fail('Pemilik dan catatan keputusan wajib diisi.');ac.contract=String(a.value);ac.decisionOwner=String(a.owner);ac.decisionNote=String(a.note);ac.decisionAt=s.run.now;event(s,'contract',`Keputusan kontrak simulasi: ${ac.contract}. ${ac.decisionNote}`);break;
case 'refund':{const fee=Number(a.fee),months=Number(a.months);if(!Number.isFinite(fee)||fee<0||!Number.isFinite(months)||months<0)return fail('Fee dan bulan harus valid.');const l=s.ledger.find(l=>l.id==='refund')!;l.refundByAccount??=Object.fromEntries(s.accounts.map(x=>[x.id,x.arr/12*.15]));l.refundByAccount[s.selected]=a.eligible?fee*months*.15:0;l.allowance=Object.values(l.refundByAccount).reduce((n,v)=>n+v,0);event(s,'refund','Provisi refund akun diperbarui; eligibility adalah asumsi eksplisit.');break;}
case 'cost':{const id=String(a.id);const amount=Number(a.amount);if(!Number.isFinite(amount)||amount<0)return fail('Biaya harus bernilai positif atau nol.');const l=s.ledger.find(l=>l.id===id);const delta=amount-(l?.allowance??0);if(a.kind!=='mandatory'&&forecast(s)+delta>750)return fail('Persetujuan opsional diblokir: forecast melebihi Rp750 juta.');if(l)l.allowance=amount;else s.ledger.push({id,category:String(a.label??id),oneOff:0,monthly:0,months:0,allowance:amount,kind:String(a.kind),committed:0,spent:0});event(s,'budget','Ledger bersama diperbarui; kewajiban wajib tetap diakui.');break;}
case 'reallocate':{const amount=Number(a.amount);const reserve=s.ledger.find(l=>l.id==='reserve')!,good=s.ledger.find(l=>l.id==='goodwill')!;if(amount<0||amount>reserve.allowance)return fail('Nilai melebihi cadangan tersedia.');reserve.allowance-=amount;good.allowance+=amount;event(s,'reallocation','Cadangan dialihkan ke goodwill tanpa menambah forecast.');break;}
}return s;}
export function restore(raw:string):State {const s=JSON.parse(raw);if(s.schemaVersion!==1||!Array.isArray(s.accounts)||s.accounts.length!==5||!s.run||!Array.isArray(s.jobs)||!Array.isArray(s.ledger)||!s.pipeline||!s.core||!Array.isArray(s.events))throw Error('Data lokal rusak atau versi tidak didukung.');return {...s,running:false};}
export const exportSession=(s:State)=>({...s,simulation:true,exportedAt:new Date().toISOString(),sourceMetadata:['Fakta kasus: Case Final Bizzit-2','Target: proposal ServeNow','Asumsi demo: PRD 1.0'],costAssumptions:'Juta IDR; 2 bulan billable; bukan penawaran vendor',running:false});
