import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();});
test('bank switches to a separate standby route rather than opening the broken main route',async({page})=>{
  await page.getByRole('button',{name:/Bank FinNusantara.*Layanan terhenti/}).click();
  await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).click();
  await expect(page.locator('.bank-question')).toBeVisible();
  await expect(page.locator('.broken-link')).toHaveCount(0);
  await page.getByRole('button',{name:'Periksa gangguan',exact:true}).click();
  await expect(page.locator('.data-motion')).toHaveAttribute('data-scene','bank');
  await expect(page.locator('.broken-link')).toBeVisible();
  await expect(page.locator('.case-store.active')).toHaveCount(0);
  const request=page.locator('.bank-request');const pos=()=>request.evaluate(e=>getComputedStyle(e).offsetDistance);
  const initial=await pos();await expect.poll(pos).not.toBe(initial);
  await page.screenshot({path:'artifacts/bank-motion-fault.png',fullPage:true});
  await page.getByRole('button',{name:'Pulihkan layanan',exact:true}).click();
  await expect(page.locator('.bank-scene')).toHaveClass(/switched/);
  await expect(page.locator('.broken-link')).toBeVisible();
  await expect(page.locator('.case-store.active')).toContainText('Pengganti');
  const transfer=page.locator('.bank-transfer').first();const move=()=>transfer.evaluate(e=>getComputedStyle(e).offsetDistance);
  const start=await move();await expect.poll(move).not.toBe(start);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'artifacts/bank-motion-recovered-mobile.png',fullPage:true});
});
test('report rejects incompatible data while retaining the old report, then publishes fresh data',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:/TeleNusa.*Laporan terlambat/}).click();
  await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).click();
  await expect(page.locator('.data-motion')).toHaveAttribute('data-scene','report');
  await expect(page.locator('.bad-record')).toHaveCount(0);
  await expect(page.locator('.report-paper')).toContainText('Data lama');
  await page.getByRole('button',{name:'Perbarui laporan',exact:true}).click();
  await expect(page.locator('.bad-record')).toBeVisible();
  await expect(page.locator('.report-paper')).toHaveClass(/old/);
  await expect(page.locator('.report-publish')).toHaveCount(0);
  await page.getByRole('button',{name:'Putar animasi data',exact:true}).click();
  const mismatch=page.locator('.bad-record');const pos=()=>mismatch.evaluate(e=>getComputedStyle(e).transform);
  const initial=await pos();await expect.poll(pos).not.toBe(initial);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'artifacts/report-motion-fault-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Perbaiki dan coba lagi'}).click();
  await expect(page.locator('.report-paper')).toHaveClass(/fresh/);
  await expect(page.locator('.report-paper')).toContainText('Data terbaru');
  await expect(page.locator('.bad-record')).toHaveCount(0);
  await expect(page.locator('.format-check')).toBeVisible();
  await page.setViewportSize({width:1440,height:900});
  await page.screenshot({path:'artifacts/report-motion-recovered.png',fullPage:true});
});
