import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/?detail=1');await page.evaluate(()=>localStorage.clear());await page.reload();});
test('S1 complete interactive journey, persistence, export and responsive screenshots',async({page})=>{
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'artifacts/overview-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Mulai demo terpandu',exact:true}).click();await page.getByRole('button',{name:'Sepakati covenant v1'}).click();
await page.locator('nav').getByText('Stabilize the Core').click();
for(const name of ['Injeksi insiden','Tetapkan Rafi sebagai incident owner','Periksa temuan diagnosis','Terapkan query / connection control','Verifikasi service & integritas'])await page.getByRole('button',{name,exact:true}).click();
await page.locator('nav').getByText('Streamline the Flow').click();await page.getByRole('button',{name:'Kirim 10 pembaruan contoh'}).click();
for(let i=0;i<8;i++)await page.getByRole('button',{name:'Jalankan 5 detik teknis'}).click();
await page.getByRole('button',{name:'Verifikasi remote',exact:true}).click();
await expect(page.locator('tbody').getByText('Selesai',{exact:true})).toHaveCount(10);
await page.getByRole('button',{name:'Pipeline data',exact:true}).click();await page.getByRole('button',{name:'Run next batch'}).click();await page.getByRole('button',{name:'Proses 3 detik'}).click();
await page.locator('nav').getByText('Restore Customer Trust').click();await page.getByRole('button',{name:'Trust Console',exact:false}).click();
await page.getByRole('button',{name:'Kumpulkan bukti'}).click();await page.getByRole('button',{name:'Validasi bukti'}).click();await page.getByLabel('Perspektif demo').selectOption('Customer reviewer');await page.getByRole('button',{name:'Terima bukti',exact:true}).click();
await expect(page.locator('tbody tr td:last-child').getByText('Diterima',{exact:true})).toHaveCount(3);
await page.getByRole('button',{name:'Renewal Decision',exact:false}).click();await page.getByLabel('Perspektif demo').selectOption('Finance / decision owner');await page.getByRole('button',{name:'Renewed · simulasi',exact:true}).click();
await page.reload();await expect(page.getByText('Dijeda',{exact:true})).toBeVisible();
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!));expect(saved.accounts[0].contract).toBe('renewed');expect(Object.values(saved.remote).reduce((v:number,r:any)=>v+r.effects,0)).toBe(10);
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Ekspor sesi',exact:true}).click();await (await download).saveAs('artifacts/session-evidence.json');
await page.goto('/?detail=1');await page.getByRole('button',{name:'Mode presentasi'}).click();await page.setViewportSize({width:1280,height:720});await page.screenshot({path:'artifacts/overview-presentation.png',fullPage:true});
await page.getByRole('button',{name:'Mode presentasi'}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/overview-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('S3 failure, safe replay, deep link and paused clock',async({page})=>{await page.getByLabel('Skenario',{exact:true}).selectOption('S3');await page.goto('/flow');await page.getByRole('button',{name:'Pipeline data',exact:true}).click();await page.getByRole('button',{name:'Run next batch'}).click();await page.getByRole('button',{name:'Proses 3 detik'}).click();let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!));expect(state.pipeline.checkpoint).toBe(100);expect(state.pipeline.status).toBe('failed');await page.getByRole('button',{name:'Koreksi mapping'}).click();await page.getByRole('button',{name:'Run next batch'}).click();await page.getByRole('button',{name:'Proses 3 detik'}).click();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!));expect(state.pipeline.checkpoint).toBe(103);await page.reload();await expect(page.getByRole('heading',{name:'Streamline the Flow'})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!).pipeline.checkpoint)).toBe(103);});
test('animation runs only while clock runs and respects reduced motion',async({page})=>{await page.getByRole('button',{name:'Start / resume'}).click();await expect(page.locator('.app')).toHaveClass(/is-running/);expect(await page.locator('.live-icon svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('signal');await page.waitForTimeout(1100);await page.getByRole('button',{name:'Pause',exact:true}).click();expect(await page.locator('.live-icon svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Start / resume'}).click();expect(await page.locator('.live-icon svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');});

test('S2 recovery has readiness guards and explicit compliance gaps',async({page})=>{
await page.getByLabel('Skenario',{exact:true}).selectOption('S2');await page.locator('nav').getByText('Stabilize the Core').click();
for(const name of ['Injeksi insiden','Tetapkan Rafi sebagai incident owner','Periksa temuan diagnosis'])await page.getByRole('button',{name,exact:true}).click();
await expect(page.getByRole('button',{name:'Jalankan failover standby'})).toBeDisabled();await page.getByRole('button',{name:'Siapkan standby & readiness check'}).click();await page.getByRole('button',{name:'Jalankan failover standby'}).click();await page.getByRole('button',{name:'Uji verifikasi gagal'}).click();await expect(page.getByRole('button',{name:'Jalankan failover standby'})).toBeEnabled();await page.getByRole('button',{name:'Jalankan failover standby'}).click();await page.getByRole('button',{name:'Verifikasi service & integritas',exact:true}).click();await page.screenshot({path:'artifacts/core-recovery.png',fullPage:true});
await page.locator('nav').getByText('Restore Customer Trust').click();await page.getByRole('button',{name:'Recovery Covenant',exact:false}).click();await page.getByRole('button',{name:'Sepakati covenant v1'}).click();await page.getByRole('button',{name:'Trust Console',exact:false}).click();for(const name of ['Muat periode bukti contoh','Kumpulkan bukti','Validasi bukti'])await page.getByRole('button',{name,exact:true}).click();await expect(page.locator('tbody').getByText('Belum ada bukti',{exact:true})).toHaveCount(2);await page.getByLabel('Perspektif demo').selectOption('Customer reviewer');await page.getByRole('button',{name:'Minta perbaikan'}).click();await expect(page.getByText('gap-1 · Arif · Account Lead')).toBeVisible();await page.screenshot({path:'artifacts/trust-evidence.png',fullPage:true});
});
test('drawers are keyboard-operable, input survives clock ticks, mobile flow remains usable',async({page})=>{
await page.getByRole('button',{name:'Fakta & target'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
await page.goto('/flow');await page.getByLabel('Entity ID',{exact:true}).fill('T-CUSTOM');await page.getByRole('button',{name:'Start / resume'}).click();await page.waitForTimeout(1200);await expect(page.getByLabel('Entity ID',{exact:true})).toHaveValue('T-CUSTOM');await page.getByRole('button',{name:'Pause',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Kirim request',exact:true}).click();await expect(page.getByText('T-CUSTOM · v1 · toko')).toBeVisible();await page.screenshot({path:'artifacts/flow-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
