import {test,expect} from '@playwright/test';
test('packets move, stop before faults, pause, and respect reduced motion',async({page})=>{
  await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();
  await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).click();
  await page.getByRole('button',{name:'Periksa gangguan',exact:true}).click();
  const motion=page.locator('.data-motion');
  await expect(motion).toHaveAttribute('data-flow-state','blocked');
  const packet=page.locator('.data-packet').first();
  const position=()=>packet.evaluate(e=>getComputedStyle(e).offsetDistance);
  const now=await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!).run.now);
  const first=await position();
  await expect.poll(position,{timeout:5000}).not.toBe(first);
  expect(await packet.evaluate(e=>getComputedStyle(e).offsetPath)).toContain('277');
  await page.getByRole('button',{name:'Jeda animasi data',exact:true}).click();
  await expect(motion).toHaveAttribute('data-motion','paused');
  await packet.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
  const paused=await position();await page.waitForTimeout(400);expect(await position()).toBe(paused);
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!).run.now)).toBe(now);
  await page.getByRole('button',{name:'Putar animasi data',exact:true}).click();
  await expect(motion).toHaveAttribute('data-motion','running');
  await page.getByRole('button',{name:'Pulihkan layanan',exact:true}).click();
  await expect(motion).toHaveAttribute('data-flow-state','flowing');
  const recovered=await position();await expect.poll(position).not.toBe(recovered);
  await page.screenshot({path:'artifacts/data-motion-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Proses 10 tiket',exact:true}).click();
  await expect(page.locator('.recovery-story')).toHaveClass(/flow-running/);
  await page.getByRole('button',{name:'Jeda animasi data',exact:true}).click();
  await expect(page.locator('.recovery-story')).not.toHaveClass(/flow-running/);
  await expect(motion).toHaveAttribute('data-motion','paused');
  await page.setViewportSize({width:390,height:844});
  await page.emulateMedia({reducedMotion:'reduce'});
  await expect(motion).toHaveAttribute('data-motion','reduced');
  expect(await packet.evaluate(e=>getComputedStyle(e).animationName)).toBe('none');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'artifacts/data-motion-mobile.png',fullPage:true});
});
