import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();});
test('simple S1: one action at a time, explicit customer acceptance, and renewal',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'artifacts/simple-desktop.png',fullPage:true});
  await expect(page.getByRole('heading',{name:/Mari pulihkan layanan/})).toBeVisible();
  await expect(page.getByRole('button',{name:'Setuju, mulai pemulihan'})).toBeVisible();
  await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).click();
  await page.getByRole('button',{name:'Periksa gangguan',exact:true}).click();
  await page.getByRole('button',{name:'Pulihkan layanan',exact:true}).click();
  await page.getByRole('button',{name:'Proses 10 tiket',exact:true}).click();
  await expect(page.locator('.recovery-story')).toHaveClass(/flow-running/);
  await page.getByRole('button',{name:'Jeda sebentar'}).click();
  await expect(page.locator('.recovery-story')).not.toHaveClass(/flow-running/);
  await page.getByRole('button',{name:'Lanjutkan proses'}).click();
  await page.getByRole('button',{name:'Pastikan hasil tiket'}).click({timeout:18000});
  await page.getByRole('button',{name:'Perbarui laporan',exact:true}).click();
  await page.getByRole('button',{name:'Lanjut ke hasil'}).click({timeout:10000});
  await page.getByRole('button',{name:'Siapkan hasil pemeriksaan'}).click();
  let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!));
  expect(saved.evidence.every((e:any)=>e.customerReview==='pending')).toBe(true);
  await page.screenshot({path:'artifacts/simple-review.png',fullPage:true});
  await page.getByRole('button',{name:'Hasil sudah sesuai'}).click();
  await page.getByRole('button',{name:'Lanjut ke keputusan'}).click();
  await page.getByRole('button',{name:'Lanjutkan kerja sama'}).click();
  saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!));
  expect(saved.accounts[0].contract).toBe('renewed');expect(saved.accounts.slice(1).every((a:any)=>a.contract==='not_started')).toBe(true);
  expect(Object.values(saved.remote).reduce((n:number,r:any)=>n+r.effects,0)).toBe(10);
  await expect(page.getByRole('heading',{name:'Terima kasih. Kita lanjut bersama.'})).toBeVisible();expect(errors).toEqual([]);
});
test('simple mobile S3: readable controls, repair and explicit review',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/simple-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).evaluate(e=>e.getBoundingClientRect().height)).toBeGreaterThanOrEqual(52);
  await page.getByRole('button',{name:/TeleNusa.*Laporan terlambat/}).click();
  await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).click();
  await page.getByRole('button',{name:'Perbarui laporan',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Laporan belum dapat diperbarui'})).toBeVisible();
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!).pipeline.checkpoint)).toBe(100);
  await page.screenshot({path:'artifacts/simple-mobile-repair.png',fullPage:true});
  await page.getByRole('button',{name:'Perbaiki dan coba lagi'}).click();
  await page.getByRole('button',{name:'Lanjut ke hasil'}).click();
  await page.getByRole('button',{name:'Siapkan hasil pemeriksaan'}).click();
  await page.getByRole('button',{name:'Minta diperbaiki'}).click();
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!).gaps.length)).toBe(1);
  await page.getByRole('button',{name:'Periksa hasil kembali'}).click();
  await page.getByRole('button',{name:'Hasil sudah sesuai'}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('simple bank keeps manual review separate, and advanced details remain available',async({page})=>{
  await page.getByRole('button',{name:/Bank FinNusantara.*Layanan terhenti/}).click();
  await page.getByRole('button',{name:'Setuju, mulai pemulihan'}).click();
  await page.getByRole('button',{name:'Periksa gangguan',exact:true}).click();
  await page.getByRole('button',{name:'Pulihkan layanan',exact:true}).click();
  await page.getByRole('button',{name:'Lihat contoh catatan'}).click();
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('servenow-v1')!).fixtures.some((f:any)=>f.manual))).toBe(false);
  await page.getByRole('button',{name:'Tambahkan contoh pemeriksaan'}).click();
  await page.getByRole('button',{name:'Lanjut ke hasil'}).click();
  await page.getByRole('button',{name:'Siapkan hasil pemeriksaan'}).click();
  await page.getByRole('button',{name:'Buka tampilan lengkap'}).click();
  await expect(page.getByRole('link',{name:'Stabilize the Core',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Tampilan sederhana',exact:true}).click();
  await expect(page.getByRole('heading',{name:/Mari pulihkan layanan/})).toBeVisible();
  await page.setViewportSize({width:1280,height:720});await page.screenshot({path:'artifacts/simple-1280.png',fullPage:true});
});
