import {useEffect,useState,type Dispatch,type ReactNode} from 'react';
import {ChevronDown,CheckCircle2,Clock3} from 'lucide-react';
import {account,cohort,currentEvidence,forecast,type Action,type Criterion,type State} from '../domain/engine';
import './details.css';
type Props={state:State;dispatch:Dispatch<Action>};
export const friendlyCriterion=(c:Criterion)=>({completion:'Pekerjaan yang sudah selesai',latency:'Waktu menyelesaikan pekerjaan',mismatch:'Pekerjaan yang belum cocok',availability:'Layanan tersedia selama periode contoh',recovery:'Pemulihan dan keutuhan data',freshness:'Usia data dalam laporan',completeness:'Kelengkapan laporan',mean:'Rata-rata waktu tanggapan layanan',error:'Permintaan yang gagal',manual:c.id==='location'?'Pemeriksaan lokasi data':c.id==='medical'?'Pemeriksaan operasional medis':'Pemeriksaan akses dan catatan layanan'}[c.metric]??c.label);
const status:Record<string,string>={accepted:'Diterima, belum diproses',queued:'Dalam antrean',running:'Sedang diproses',retry_wait:'Menunggu percobaan berikutnya',needs_verification:'Hasil perlu dipastikan',needs_attention:'Perlu diperbaiki',succeeded:'Selesai dan dipastikan',missing:'Bukti belum tersedia',collected:'Siap diperiksa',customer_review_pending:'Memenuhi ukuran, menunggu pelanggan',incomplete:'Periode bukti belum cukup',failed:'Belum memenuhi ukuran',outdated:'Kesepakatan lama',published:'Laporan terbaru tersedia',extracting:'Memeriksa data',idle:'Belum diperbarui'};
export function DetailSection({title,children}:{title:string;children:ReactNode}){return <details className="easy-detail-section"><summary>{title}<ChevronDown size={21}/></summary><div className="easy-detail-body">{children}</div></details>}
export function AgreementDetails({state:s,dispatch:d}:Props){
 const ac=account(s);const [criteria,setCriteria]=useState(()=>structuredClone(ac.criteria));
 useEffect(()=>setCriteria(structuredClone(ac.criteria)),[s.selected,ac.version]);
 const update=(i:number,patch:Partial<Criterion>)=>setCriteria(v=>v.map((c,n)=>n===i?{...c,...patch}:c));
 return <DetailSection title="Atur ukuran keberhasilan"><p>Kesepakatan untuk {ac.name}. Jika diubah, hasil perlu diperiksa dan disetujui kembali.</p><form onSubmit={e=>{e.preventDefault();d({type:'editCovenant',criteria});}}>
 {criteria.map((c,i)=><fieldset key={c.id}><legend>{friendlyCriterion(c)}</legend><div className="easy-form-grid"><label>Batas yang disepakati<select value={c.op} onChange={e=>update(i,{op:e.target.value as Criterion['op']})}><option value="<">Kurang dari</option><option value="<=">Paling banyak</option><option value=">=">Paling sedikit</option><option value="=">Tepat</option></select></label><label>Nilai ({c.unit})<input required type="number" min="0" step="any" value={c.threshold} onChange={e=>update(i,{threshold:e.target.valueAsNumber})}/></label><label>Lama pengamatan (detik)<input required type="number" min="0" value={c.duration} onChange={e=>update(i,{duration:e.target.valueAsNumber})}/></label><label>Pemeriksa<input required value={c.reviewer} onChange={e=>update(i,{reviewer:e.target.value})}/></label><label className="full-field">Pengecualian<input value={c.exclusions} onChange={e=>update(i,{exclusions:e.target.value})}/></label></div></fieldset>)}
 <p className="easy-hint">604.800 detik = 7 hari contoh. Nol berarti memakai lama simulasi ini.</p><button className="easy-secondary" type="submit">Simpan ukuran baru</button></form><p>Kesepakatan versi {ac.version} · {ac.agreed?'Sudah disepakati':'Perlu disepakati'}</p>{!ac.agreed&&<button onClick={()=>d({type:'agree'})}>Sepakati ukuran ini</button>}</DetailSection>;
}
export function ServiceDetails({state:s,dispatch:d}:Props){
 const [owner,setOwner]=useState('Rafi · Tim pemulihan');const incident=s.core.incident;
 const stages=['detected','assigned','diagnosed','verifying','resolved'];
 return <DetailSection title="Lihat penanganan layanan"><p>Penanganan ini berlaku untuk layanan bersama. Tiket baru dapat dikerjakan setelah layanan dan keutuhan data diperiksa.</p><ol className="easy-timeline">{['Gangguan ditemukan','Penanggung jawab ditetapkan','Penyebab diperiksa','Perbaikan dijalankan','Hasil dipastikan'].map((label,i)=><li key={label} className={stages.indexOf(incident)>=i?'done':''}>{stages.indexOf(incident)>=i?<CheckCircle2 size={20}/>:<Clock3 size={20}/>}<span>{label}</span></li>)}</ol>
 <div className="easy-form-grid"><label>Penanggung jawab<input value={owner} onChange={e=>setOwner(e.target.value)}/></label><div><p>Beban aplikasi: <strong>{s.core.samples.at(-1)?.cpu}%</strong></p><p>Jalur data terpakai: <strong>{s.core.samples.at(-1)?.db}%</strong></p></div></div>
 {s.run.scenario==='S2'&&<p>Penyimpanan pengganti: {s.core.standby?'siap dan diperiksa':'belum disiapkan'}. Salinan pemulihan: {s.core.backup?'tersedia':'belum tersedia'}. Salinan untuk membaca data belum dikonfigurasi.</p>}
 <div className="easy-actions">{s.run.scenario==='S2'&&<button disabled={s.core.standby} onClick={()=>d({type:'prepare'})}>Siapkan penyimpanan pengganti</button>}<button disabled={incident!=='none'||s.run.scenario==='S2'&&!s.core.readiness} onClick={()=>d({type:'inject'})}>Mulai contoh gangguan</button><button disabled={incident!=='detected'||!owner.trim()} onClick={()=>d({type:'assign',owner})}>Tugaskan penanggung jawab</button><button disabled={incident!=='assigned'} onClick={()=>d({type:'diagnose'})}>Periksa penyebab</button><button disabled={incident!=='diagnosed'||s.run.scenario==='S2'&&!s.core.readiness} onClick={()=>d({type:'recover'})}>{s.run.scenario==='S2'?'Pindah ke penyimpanan pengganti':'Atur beban layanan'}</button>{s.run.scenario==='S2'&&<button disabled={incident!=='diagnosed'||!s.core.backup} onClick={()=>d({type:'recover',playbook:'restore'})}>Pulihkan dari salinan</button>}<button disabled={incident!=='verifying'} onClick={()=>d({type:'verifyCore'})}>Pastikan layanan dan data aman</button><button disabled={incident!=='verifying'} onClick={()=>d({type:'verifyCore',failed:true})}>Coba hasil pemeriksaan gagal</button></div><p className="easy-hint">Tombol aktif mengikuti urutan di atas. Pemeriksaan gagal mengembalikan penanganan ke tahap diagnosis. Pengaturan ini adalah contoh, bukan sistem produksi.</p></DetailSection>;
}
export function WorkDetails({state:s,dispatch:d}:Props){
 const jobs=cohort(s);const [filter,setFilter]=useState('all'),[entity,setEntity]=useState('T-01'),[version,setVersion]=useState(1),[payload,setPayload]=useState('Pembaruan status tiket'),[mode,setMode]=useState('async'),[fault,setFault]=useState('none'),[commitFail,setCommitFail]=useState(false);
 return <><DetailSection title={`Lihat pekerjaan satu per satu (${jobs.length})`}><p>Diterima berarti pekerjaan sudah dicatat. Selesai berarti hasilnya sudah dipastikan.</p><label>Tampilkan pekerjaan<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua pekerjaan</option>{['accepted','queued','running','retry_wait','needs_verification','needs_attention','succeeded'].map(v=><option key={v} value={v}>{status[v]}</option>)}</select></label><div className="easy-records">{jobs.filter(j=>filter==='all'||j.status===filter).map(j=><article key={j.id}><strong>{j.entityId} · pembaruan {j.version}</strong><p>{status[j.status]} · {j.attempts} percobaan</p><p>Waktu: {(j.completedAt??s.run.now)-j.acceptedAt} detik dari batas 60 detik.</p>{j.status==='needs_verification'&&<button onClick={()=>d({type:'verifyJob',id:j.id})}>Pastikan hasil {j.entityId}</button>}{j.status==='needs_attention'&&<button onClick={()=>d({type:'retry',id:j.id})}>Perbaiki {j.entityId}</button>}<details><summary>Catatan pekerjaan</summary><p>{j.reason}</p><p>Nomor catatan: {j.id}. Pengiriman {s.outbox.find(o=>o.jobId===j.id)?.state==='dispatched'?'sudah diteruskan':'tersimpan, menunggu diteruskan'}.</p></details></article>)}</div>{jobs.filter(j=>filter==='all'||j.status===filter).length===0&&<p>Belum ada pekerjaan dalam pilihan ini.</p>}</DetailSection>
 <DetailSection title="Coba satu pekerjaan tambahan"><form onSubmit={e=>{e.preventDefault();d({type:'submit',entity,version,payload,mode,fault,commitFailed:commitFail});}}><div className="easy-form-grid"><label>Nomor tiket<input required value={entity} onChange={e=>setEntity(e.target.value)}/></label><label>Urutan pembaruan<input required type="number" min="1" value={version} onChange={e=>setVersion(e.target.valueAsNumber)}/></label><label className="full-field">Isi pembaruan<input required value={payload} onChange={e=>setPayload(e.target.value)}/></label><label>Cara menangani<select value={mode} onChange={e=>setMode(e.target.value)}><option value="async">Catat dahulu, kerjakan bergiliran</option><option value="sync">Harus mendapat jawaban langsung</option></select></label><label>Kondisi contoh<select value={fault} onChange={e=>setFault(e.target.value)}><option value="none">Normal</option><option value="transient">Gangguan sementara</option><option value="ambiguous">Balasan tidak diterima</option><option value="permanent">Data perlu diperbaiki</option><option value="exhausted">Gagal sampai batas percobaan</option></select></label></div><label className="easy-checkbox"><input type="checkbox" checked={commitFail} onChange={e=>setCommitFail(e.target.checked)}/>Coba pencatatan awal gagal</label><button className="easy-secondary" type="submit">Kirim pekerjaan contoh</button></form><label className="easy-checkbox"><input type="checkbox" checked={s.publisherFailed} onChange={e=>d({type:'publisher',failed:e.target.checked})}/>Jeda penerusan pekerjaan yang sudah dicatat</label><label>Pekerjaan yang boleh berjalan bersamaan<select value={s.workers} onChange={e=>d({type:'workers',value:+e.target.value})}><option value="1">Satu pekerjaan</option><option value="2">Dua pekerjaan</option><option value="4">Coba empat — melebihi batas</option></select></label><p>Maksimal dua pekerjaan bersamaan. Menambah pekerjaan tidak memperbaiki layanan yang sedang gagal.</p><button onClick={()=>d({type:'advance',seconds:5})}>Jalankan 5 detik contoh</button></DetailSection>
 <DetailSection title="Lihat isi dan usia laporan"><p>{status[s.pipeline.status]}. Data lengkap hingga {s.pipeline.through<0?'12 jam sebelum simulasi':`detik ${s.pipeline.through} simulasi`}.</p><dl className="easy-pairs"><div><dt>Usia data</dt><dd>{Math.round((s.run.now-s.pipeline.through)/60)} menit</dd></div><div><dt>Perubahan terakhir yang tersimpan</dt><dd>{s.pipeline.checkpoint}</dd></div><div><dt>Sumber yang tercakup</dt><dd>{s.pipeline.coverage.join(' dan ')}</dd></div><div><dt>Kelengkapan pembaruan</dt><dd>{s.pipeline.status==='published'?'3 dari 3 perubahan':'Belum dipastikan'}</dd></div><div><dt>Terakhir diterbitkan</dt><dd>{s.pipeline.publishedAt<0?'Sebelum simulasi':`Detik ${s.pipeline.publishedAt}`}</dd></div><div><dt>Terakhir tampilan dimuat ulang</dt><dd>Detik {s.pipeline.refreshAt}</dd></div></dl><p>Contoh perubahan: tiket T-01 diperbarui, T-02 datang terlambat, dan T-03 dihapus.</p><div className="easy-records">{Object.entries(s.pipeline.rows).map(([id,v])=><article key={id}><strong>{id}</strong><p>Pembaruan {v} tersimpan dalam laporan.</p></article>)}</div><div className="easy-actions"><button disabled={s.core.status!=='healthy'||s.pipeline.finishAt!==null} onClick={()=>d({type:'batch'})}>Periksa pembaruan laporan</button><button disabled={s.pipeline.mapping} onClick={()=>d({type:'mapping'})}>Perbaiki format laporan</button><button onClick={()=>d({type:'advance',seconds:3})}>Jalankan 3 detik contoh</button><button onClick={()=>d({type:'refresh'})}>Muat ulang tampilan laporan</button></div><p className="easy-hint">Memuat ulang tampilan tidak memperbarui datanya. Pemeriksaan otomatis dijadwalkan setiap 5 menit simulasi saat layanan siap.</p></DetailSection></>;
}
export function EvidenceDetails({state:s,dispatch:d}:Props){const ac=account(s),ev=currentEvidence(s);return <DetailSection title="Periksa bukti dan kekurangannya"><p>Untuk {ac.name}, kesepakatan versi {ac.version}, sesi {s.run.id}. Hasil pemeriksaan belum berarti pelanggan menyetujuinya.</p><div className="easy-records">{ac.criteria.map(c=>{const e=ev.find(e=>e.criterionId===c.id);return <article key={c.id}><strong>{friendlyCriterion(c)}</strong><p>{e?.value==null?'Belum ada hasil':`${Number(e.value.toFixed(3))} ${e.unit}`} · target {c.op} {c.threshold} {c.unit}</p><p>{e?.validation==='accepted'?'Sudah diterima pelanggan':status[e?.validation??'missing']}</p>{e&&<details><summary>Asal bukti dan pemeriksa</summary><p>{e.window.duration===604800?'Catatan 7 hari contoh':`${e.window.duration} detik simulasi`}. Penanggung jawab: {e.owner}. Pemeriksa: {c.reviewer}.</p><p>{e.provenance}</p><ul>{e.sourceRefs.map(id=><li key={id}>{id.startsWith('fixture')?'Catatan pengamatan atau pemeriksaan contoh':s.events.find(x=>x.id===id)?.message??id}</li>)}</ul></details>}</article>;})}</div><div className="easy-actions"><button onClick={()=>{d({type:'generate'});d({type:'validate'});}}>Periksa ulang semua bukti</button><button onClick={()=>d({type:'fixture'})}>Tambahkan catatan 7 hari contoh</button><button onClick={()=>d({type:'fixture',failing:true})}>Coba catatan dengan lebih banyak kegagalan</button>{ac.criteria.some(c=>c.metric==='manual')&&<button onClick={()=>d({type:'fixture',manual:true})}>Tambahkan pemeriksaan manual contoh</button>}</div><p className="easy-hint">Catatan contoh bukan pengamatan produksi. Pemeriksaan manual tidak membuktikan sertifikasi keamanan atau kelayakan medis.</p>{s.gaps.filter(g=>g.accountId===s.selected).map(g=><p key={g.id}>Perlu ditindaklanjuti oleh {g.owner}: {g.note}</p>)}<details><summary>Keputusan pemeriksaan terdahulu</summary>{s.evidence.filter(e=>e.accountId===s.selected&&!ev.includes(e)).map(e=><p key={e.id}>Sesi {e.runId}, versi {e.covenantVersion}: {e.customerReview==='accepted'?'pernah diterima':e.customerReview==='rejected'?'perbaikan diminta':'belum diputuskan'}. {status[e.validation]??'Catatan lama'}.</p>)}</details></DetailSection>}
export function BudgetDetails({state:s,dispatch:d}:Props){
 const ac=account(s);const [amount,setAmount]=useState(25),[mandatory,setMandatory]=useState(false),[fee,setFee]=useState(ac.arr/12),[months,setMonths]=useState(1),[eligible,setEligible]=useState(false);
 useEffect(()=>{setFee(ac.arr/12);setEligible(false);},[s.selected]);
 const money=(n:number)=>`Rp${n.toLocaleString('id-ID',{maximumFractionDigits:2})} juta`;
 const categories:Record<string,string>={core:'Pemulihan layanan',flow:'Pekerjaan dan laporan',ops:'Operasional bersama',refund:'Cadangan pengembalian biaya',goodwill:'Bantuan tambahan',reserve:'Cadangan darurat'};
 return <DetailSection title="Lihat dan atur biaya pemulihan"><p>Satu anggaran untuk seluruh pelanggan selama 60 hari. Batasnya Rp750 juta.</p><dl className="easy-pairs"><div><dt>Rencana biaya</dt><dd>{money(forecast(s))}</dd></div><div><dt>{forecast(s)>750?'Melebihi anggaran':'Sisa anggaran'}</dt><dd>{money(Math.abs(750-forecast(s)))}</dd></div><div><dt>Biaya yang sudah disepakati</dt><dd>{money(s.ledger.reduce((v,l)=>v+l.committed,0))}</dd></div><div><dt>Biaya yang sudah dibayar</dt><dd>{money(s.ledger.reduce((v,l)=>v+l.spent,0))}</dd></div></dl>
 {s.ledger.map(l=><details key={l.id} className="easy-cost-row"><summary>{categories[l.id]??l.category}<strong>{money(l.oneOff+l.monthly*l.months+l.allowance)}</strong></summary><p>Sekali bayar: {money(l.oneOff)}. Bulanan: {money(l.monthly)} × {l.months} bulan. Cadangan: {money(l.allowance)}.</p></details>)}<p>Setelah hari ke-60, biaya berulang contoh sebesar Rp40 juta per bulan. Rencana biaya dan cadangan belum berarti uang sudah dibayar.</p>
 <form onSubmit={e=>{e.preventDefault();d({type:'cost',id:mandatory?'mandatory-extra':'goodwill',amount,kind:mandatory?'mandatory':'optional',label:'Kewajiban wajib tambahan'});}}><fieldset><legend>Atur bantuan atau kewajiban tambahan</legend><label>Jumlah rencana biaya (juta rupiah)<input required type="number" min="0" step="any" value={amount} onChange={e=>setAmount(e.target.valueAsNumber)}/></label><label className="easy-checkbox"><input type="checkbox" checked={mandatory} onChange={e=>setMandatory(e.target.checked)}/>Ini kewajiban yang harus dicatat</label><div className="easy-actions"><button type="submit">Simpan rencana biaya</button><button type="button" onClick={()=>d({type:'reallocate',amount})}>Pindahkan cadangan ke bantuan</button></div><p>Bantuan tambahan ditolak jika melampaui anggaran. Kewajiban tetap dicatat meski anggaran terlampaui.</p></fieldset></form>
 <form onSubmit={e=>{e.preventDefault();d({type:'refund',fee,months,eligible});}}><fieldset><legend>Pengembalian biaya untuk {ac.name}</legend><div className="easy-form-grid"><label>Biaya langganan per bulan (juta rupiah)<input required type="number" min="0" step="any" value={fee} onChange={e=>setFee(e.target.valueAsNumber)}/></label><label>Jumlah bulan terdampak<input required type="number" min="0" step="any" value={months} onChange={e=>setMonths(e.target.valueAsNumber)}/></label></div><label className="easy-checkbox"><input type="checkbox" checked={eligible} onChange={e=>setEligible(e.target.checked)}/>Memenuhi syarat kontrak dalam contoh ini</label><p>15% × {money(fee)} × {months} bulan = <strong>{money(eligible?fee*months*.15:0)}</strong></p><button type="submit">Simpan pengembalian biaya</button><p className="easy-hint">Syarat bulanan harus diperiksa terpisah. Catatan 7 hari tidak otomatis membuktikan hak pengembalian biaya.</p></fieldset></form></DetailSection>;
}
const eventNames:Record<string,string>={run:'Contoh pemulihan baru dimulai',covenant_agreed:'Ukuran keberhasilan disepakati',covenant_changed:'Ukuran keberhasilan diubah',prepared:'Penyimpanan pengganti siap',incident:'Gangguan ditemukan',assigned:'Penanggung jawab ditetapkan',diagnosed:'Penyebab gangguan diperiksa',recovery_action:'Perbaikan dijalankan',verified:'Layanan dan data sudah diperiksa',verification_failed:'Pemeriksaan gagal; penanganan diulang',outbox:'Pekerjaan dicatat dengan aman',accepted:'Pekerjaan diterima',dispatch:'Pekerjaan diteruskan',running:'Pekerjaan mulai diproses',attempt_failed:'Percobaan belum berhasil',succeeded:'Pekerjaan selesai',needs_verification:'Hasil pekerjaan perlu dipastikan',reconciled:'Hasil pekerjaan sudah dicocokkan',corrected:'Pekerjaan diperbaiki',batch_failed:'Format data tidak cocok',published:'Laporan terbaru diterbitkan',extract:'Pembaruan laporan diperiksa',mapping:'Format data diperbaiki',fixture:'Catatan contoh ditambahkan',evidence:'Bukti disiapkan',validation:'Bukti diperiksa',accepted_evidence:'Pelanggan menerima hasil',correction:'Pelanggan meminta perbaikan',contract:'Keputusan kerja sama dicatat',budget:'Rencana biaya diperbarui',refund:'Pengembalian biaya diperbarui',reallocation:'Cadangan dialihkan',intent:'Keinginan pelanggan dicatat'};
export function HistoryDetails({state:s}:Pick<Props,'state'>){const [all,setAll]=useState(false);return <DetailSection title="Lihat riwayat dan penanggung jawab"><label className="easy-checkbox"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Sertakan sesi dan pelanggan lain</label><ol className="easy-history">{s.events.filter(e=>all||e.runId===s.run.id&&(e.accountId===s.selected||e.accountId==='platform')).slice().reverse().map(e=><li key={e.id}><strong>{eventNames[e.type]??'Catatan pekerjaan diperbarui'}</strong><span>{e.accountId==='platform'?'Layanan bersama':s.accounts.find(a=>a.id===e.accountId)?.name} · detik {e.simulatedAt} · {e.runId}</span></li>)}</ol>{!s.events.length&&<p>Belum ada tindakan. Mulai pemulihan untuk mencatat langkah pertama.</p>}</DetailSection>}
